export type {
  AboutBlockProps,
  ContactBlockProps,
  FeatureItem,
  FeaturesBlockProps,
  GalleryBlockProps,
  GalleryItem,
  HeroBlockProps,
  HeroCta,
  HeroMedia,
} from '@/lib/schema/blocks';
export {
  AboutBlockSchema,
  ContactBlockSchema,
  FeatureItemSchema,
  FeaturesBlockSchema,
  GalleryBlockSchema,
  GalleryItemSchema,
  hasAboutContent,
  hasContactContent,
  hasFeaturesContent,
  HeroBlockSchema,
  HeroCtaSchema,
  HeroMediaSchema,
} from '@/lib/schema/blocks';
